# Generated by Django 2.2 on 2021-10-21 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211021_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 13, 52, 21, 230195)),
        ),
    ]
