# Generated by Django 2.2 on 2021-10-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
